### ISSUE TITLE
Metrumatoran.ttf didn't work as Terminal font.

### ISSUE THREAD

**Issue by fabianmendes** [MtMNC/Bionicle-Fonts#3]
Hi, excuse me. After a long time, I finally could use your fonts, and there was a problem. I wanted to use them for my Ubuntu 18.04 TERMINAL font but there nothing happen; I tried to use it as interface font and worked properly but in the Terminal. You could see in the images, attached, that the Voyamatoran worked, without proper space between letter, nevermind, did well! 👍

![captura de pantalla de 2018-09-15 18-40-55](https://user-images.githubusercontent.com/31230743/45591140-4eaac180-b917-11e8-94c1-ed634f4dc730.png)
![captura de pantalla de 2018-09-15 18-41-26](https://user-images.githubusercontent.com/31230743/45591141-4f435800-b917-11e8-8a76-2755b7b99a92.png)

**Comment by MtMNC** [comment]
You have quite some dedication if you want to use Matoran text for your terminal!

Offhand, I'm not sure why one would work but not the other. I built the fonts using Fontello, and I think I used the same settings for both fonts. I can try rebuilding the fonts at some point, but I probably won't have time for several weeks.

**Comment by fabianmendes** [comment]
Oh, alright, don't worry. Just having fun because seems to be cool doing
all the work in that font!

Also, It does not bother me, indeed I wanted to protect my terminal with
something, any way, and actually this is quite perfect.
If you want to, I suggest do it when you were more "free", like checking
coding or reading an article while eating the lunch haha.

Sincerely,

 ~V. Fabian T. Mendes C.

**Comment by fabianmendes** [comment]
Nevermind, It resolved itself after update and upgrade.. I don't know, kid of weird. Thanks, hope could help ya with something else you need.

**Comment by MtMNC** [comment]
I'm glad it's working!

**Comment by fabianmendes** [comment]
I'm very glad too. Thanks, also, when you can and got ready; feel free to Merge my fork, you can see the few updates. Happy weekend!

![capture](https://user-images.githubusercontent.com/31230743/45918635-eea4a580-be57-11e8-9462-46d2ffd399c4.png)
Take a look, @MtMNC hehe. Loved it.
